#!/bin/bash


read -p "This will install CROUTON and SHADOWROOT on your chromebook.  Proceed? y/N?" -n 1 -r
echo    # (optional) move to a new line
if [[ $REPLY =~ ^[Yy]$ ]]
then
    # do dangerous stuff


u=`getent passwd "1000" | cut -d: -f1`

#Make sure we are root to setup the chroot
if [[ $UID != 0 ]]; then
    echo "Please run this script with sudo or root privileges."
    echo "sudo $0 $*"
    exit 1
else

echo -e "\e[30;48;5;226mShadowRoot\e[0m: Downloading latest crouton installer"
curl -L https://goo.gl/fd3zc -o /home/$u/user/Downloads/crouton

echo -e "\e[30;48;5;226mShadowRoot\e[0m: Installing crouton installer to host"
sudo install -Dt /usr/local/bin -m 755 /home/$u/user/Downloads/crouton

echo -e "\e[30;48;5;226mShadowRoot\e[0m: Installing Ubuntu Bionic core to crouton"
sudo crouton -t core -r bionic

echo -e "\e[30;48;5;226mShadowRoot\e[0m: Running update on core to prevent errors"
sudo crouton -u -t core -r bionic

echo -e "\e[30;48;5;226mShadowRoot\e[0m: Installing xserver to prevent errors"
#apt-get install -y --no-install-recommends xserver-xorg-video-all xserver-xorg xserver-xorg-video-intel nano git
sudo enter-chroot -x sh -c "export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin ; apt-get install -y --no-install-recommends xserver-xorg-video-all xserver-xorg xserver-xorg-video-intel nano git"

echo -e "\e[30;48;5;226mShadowRoot\e[0m: Installing XFCE window manager to crouton"
sudo crouton -u -t xfce -r bionic

echo -e "\e[30;48;5;226mShadowRoot\e[0m: Updating keyboard configuration in crouton"
sudo crouton -r ubuntuversion -t keyboard -u

#figfure out the PWD of enter-chroot -x
#sudo enter-chroot -x sh -c "export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin ; cd /root;git clone https://github.com/gtxaspec/shadowroot;cd shadowroot;./chromeroot.sh"

#set permissions of app image to user

#sudo enter-chroot -x apt-get install -y --no-install-recommends xserver-xorg-video-all xserver-xorg xserver-xorg-video-intel nano git

echo -e "\e[30;48;5;226mShadowRoot\e[0m: Ready.  enter crouton by typing: sudo startxfce4"

fi

fi
