#!/bin/bash

#Make sure we are root to proceed with installing libraries

if [[ $UID != 0 ]]; then
    echo "Please run this script with sudo or root privileges."
    echo "sudo $0 $*"
    exit 1
else

#if we run as sudo, then run from the install directory inside /root, if not, run from wherever $PWD is.
if [[ "$0" == "/usr/local/bin/driver_install_ihd" ]]; then
DIR=/root/shadowroot/
else
DIR=
fi

echo "Installing intel media driver for Intel 8th Generation + Graphics"

#copy, extract, and install intel video driver
cp "$DIR"iHD_drv_video.so.gz /tmp/
gzip -d /tmp/iHD_drv_video.so.gz
cp /tmp/iHD_drv_video.so /usr/lib/x86_64-linux-gnu/dri/

#copy, extract, and install libigdgmm to the intel driver works
cp "$DIR"libigdgmm.so.11.1.0.gz /tmp/
gzip -d /tmp/libigdgmm.so.11.1.0.gz
cp /tmp/libigdgmm.so.11.1.0 /usr/lib/x86_64-linux-gnu/
ln -s /usr/lib/x86_64-linux-gnu/libigdgmm.so.11.1.0 /usr/lib/x86_64-linux-gnu/libigdgmm.so.11
ln -s /usr/lib/x86_64-linux-gnu/libigdgmm.so.11 /usr/lib/x86_64-linux-gnu/libigdgmm.so

#install dependencies for libva compilation
apt-get install -y --no-install-recommends autoconf libtool libdrm-dev autotools-dev automake

#download, compile and install libva
cd /root
git clone https://github.com/intel/libva.git
cd libva
./autogen.sh --prefix=/usr --libdir=/usr/lib/x86_64-linux-gnu
make
make install

#delete temp files
rm -f /tmp/libigdgmm.so.11.1.0
rm -f /tmp/iHD_drv_video.so

#add exports to env so it works as the user
echo LIBVA_DRIVERS_PATH=/usr/lib/x86_64-linux-gnu/dri >> /etc/environment
echo LIBVA_DRIVER_NAME=iHD >> /etc/environment

echo "Installation complete, please log out of crouton, and log back in for changes to be effective."

fi
