#!/bin/bash

function custom_script() {
    echo -e "\e[30;48;5;226mCUSTOM ENABLED, custom.sh will be RUN!\e[0m"
    CUSTOM="sudo /home/shadow-user/custom.sh &"
}

function debug_console_log() {
    echo -e "\e[30;48;5;226mDEBUG ENABLED, ALL LOGS WILL BE PASSED TO THE CONSOLE!\e[0m"
    DEBUG1="tail -F ~/.cache/blade/shadow/shadow-launcher.log &"
    DEBUG2="tail -F ~/.cache/blade/shadow/shadow.log &"
}

function schroot_init() {
        echo -e "\e[30;48;5;226mShadowRoot\e[0m: Beginning chroot session, session name:"
        schroot --begin-session --chroot shadowroot --session-name shadow-beta
        echo -e "\e[30;48;5;226mShadowRoot\e[0m: Running Shadow in chroot"
        schroot --run-session --chroot shadow-beta --directory /home/shadow-user -- /bin/su shadow-user -c "$DEBUG1 $DEBUG2 $CUSTOM /home/shadow-user/AppImage/ShadowBeta.AppImage --no-sandbox"
        echo -e "\e[30;48;5;226mShadowRoot\e[0m: Ending chroot session"
        schroot --end-session --chroot shadow-beta
}

trap ctrl_c INT
function ctrl_c() {
        echo -e "\e[30;48;5;226mShadowRoot\e[0m: Ending chroot session"
        schroot --end-session --chroot shadow-beta
}

if { [ "$1" == "--custom" ] && [ "$2" == "--debug" ]; } || { [ "$1" == "--debug" ] && [ "$2" == "--custom" ]; } then
	custom_script
	debug_console_log
elif [ "$1" = "--custom" ]; then
	custom_script
elif [ "$1" = "--debug" ]; then
	debug_console_log
fi

   echo -e "Welcome to \e[30;48;5;226mShadowRoot\e[0m!"
   echo -e "\e[30;48;5;226mShadowRoot\e[0m: Loading, please wait..."

   #File discriptor to display function's output to the console in real time
   exec 3>&1
   #Check for a client update, if there is, after patching is done, restart the client
   if [[ $(schroot_init | tee /dev/fd/3) == *downloaded* ]]; then
       echo -e "\e[30;48;5;226mShadowRoot\e[0m: Update Found, restarting Shadow..."
       schroot_init
       exit 1;
   fi
       #Clean up the file discriptor, close it
       exec 3>&-
